window.ker = [
  {
    num: 0,
    name: "Erdőszél",
    desc: "Egészséges, pihentető túrák, hőssegédek és bűvös lények otthona.",
    x: 1,
    y: 1,
    pop: Math.floor(1 + Math.random() * 100),
    mtn: 0,
    exp: 0,
    niv: Math.floor(30 + Math.random() * 30),
    joy: Math.floor(70 + Math.random() * 30),
    def: Math.floor(40 + Math.random() * 30),
    ufo: 70,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: .7,
    defo: 1,
    culto: 1,
    vélemény: [
      {
        cond: "ufo_>_500",
        duma: ["Kicsit furák ezek az erdei lények. Neked nem?",
          "kjh[ÄfsdfđĐ[đĐ... Én... vagyok... ihbdifurigk... Nem.",
          "Éjjelente olyan, mintha mozognának a fák! Hátborzongató!",
          "Bzzzzzzz... Mezonscanelésem szerint most már agytumorod van!",
          "Bübü! Bübü! Gurgurgul. Etejóka, pípíííí!",
          "Egyre több itt az új faj. Vajon mutánsok vagy földönkívüliek?"]
      },
      {
        cond: "had_<_-50",
        duma: ["Félek tőlük! Rettegek! Ott vannak mindenhol!",
          "Eleinte még aranyosak voltak ezek a lények, de most már egyre agresszívebbek!",
          "Itt van például ez a mosolygós kis fa... Ááááá! Letépte a karom!!! A barom!!!",
          "Üdvözöllek, földlakó! Mi vagyunk szadisták. Elpusztítunk titeket!",
          "Csináljon valamit, polgi! Ezek az erdei lények kinyírnak minket!!!",
          "Meghackelik a gondolatainkat és olyan büdöseket finganak, hogy el lehet tőle kárhozni!"]
      },
      {
        cond: "joy_<_20",
        duma: ["Ez egy bűnös hely. Egy bűnös város.",
          "Én már csak egy megfelelő fát meg kötelet keresek...",
          "Utállak téged! Bíztunk benned, de csalódtunk! Takarodj!",
          "Szerinted miért élek itt? Lehet abban a rothadó városban élni??!!",
          "Ez korábban egy üde, kellemes hely volt, de tönkretetted!"]
      },
      {
        cond: "niv_<_20",
        duma: ["No money, no problem!",
          "A romlott társadalom anyagilag tönkretett. Most itt próbálok békére találni.",
          "Éppenséggel élhetnénk itt is egy kicsit magasabb színvonalon. Ez még nem a mélydzsungel!",
          "Ennyi pénzből nem lehet utánpótlást nevelni! Mi lesz így a sporttal?"]
      },
      {
        cond: "pop_<_100",
        duma: ["Jó ez a csend és nyugalom, de lassan kihalunk...",
          "Mindig erre a magányra vágytam!",
          "Jé, egy ember!"]
      },
      {
        cond: "def_>_100",
        duma: ["Minek ide ennyi rendőr? Itt mi békében élünk az erdei lényekkel!",
          "A sok egyenruhás fickó már veszélyezteti az erdő szabad világát!"]
      },
      {
        cond: "pop_>_2500",
        duma: ["Sosem volt ilyen tömegnyomor itt!",
          "Nem lehet már nyugodtan szarni a bokorban, annyian vannak!",
          "Elveszett a régi csend és nyugalom!"]
      },
      {
        cond: "joy_>_75",
        duma: ["Itt végre megtaláltam a belső békém.",
          "Sej-haj, oly vidám a vándor élet!",
          "Jöjjön, mutatok egy gyönyörű tájat!",
          "Ez a legjobb hely az egész városban!",
          "A boldogság titka: az Erdőszél!"]
      },
    ],
    semmi: [
      "Ha ön a polgármester, igazán fejleszthetné ezt az elvadult környéket!",
      "Éppen hugyoznék... Nem tudsz másvalakit kérdezni?",
      "Fütyfürüty! Szép az élet, csicseregnek a madarak! Madarak?",
      "A legfontosabb a tiszta sport és a minőségi utánpótlás-nevelés!",
      "Üdv! Ügyes Frigyes vagyok, az ezermester! Mit kell elintézni?",
      "Az ember kijön ide békésen meditálni... Erre a pofájába nyomnak egy mikrofont!",
      "Mi van? Nem voltál még erdőben? Hát milyen lenne?",
      "Érdekes itt az élővilág. Szerinted ez növény vagy állat?",
      "A legfontosabb a szeretet. Akit szeretsz, az sosem hal meg!",
      "Ha Isten nem Szentháromság, akkor nincs értelme a teremtésnek.",
      "Cssssss! Hallgasd a természet hangjait...",
      "Megmutatom, hogy lehet természetes módszerekkel, köveket verve igazi ökölvívóvá válni!",
      "Itt születnek a valódi legendák és a... favágók!"
    ]
  },
  {
    num: 1,
    name: "Farmok",
    desc: "Szorgos, egyszerű gazdálkodók földjei.",
    x: 2,
    y: 1,
    pop: Math.floor(100 + Math.random() * 400),
    mtn: 0,
    exp: 0,
    niv: Math.floor(5 + Math.random() * 25),
    joy: Math.floor(25 + Math.random() * 50),
    def: Math.floor(35 + Math.random() * 30),
    ufo: 50,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: .7,
    defo: .7,
    culto: 1,
    vélemény: [
      {
        cond: "ufo_>_100",
        duma: ["Jól vagyunk. Csak néha jönnek óriások le a hegyről."
        ]
      },
      {
        cond: "had_<_-50",
        duma: []
      },
      {
        cond: "joy_<_20",
        duma: []
      },
      {
        cond: "niv_<_20",
        duma: []
      },
      {
        cond: "pop_<_100",
        duma: []
      },
      {
        cond: "def_>_100",
        duma: []
      },
      {
        cond: "pop_>_2500",
        duma: []
      },
      {
        cond: "joy_>_75",
        duma: []
      },
    ],
    semmi: [
      "Kicsit büdös van, de azért... hát, csak büdös van, na!",
      "Pillanat, még megetetem a tyúkokat...",
      "Osztán minek köszönhetjük a látogatást?",
      "Hogy szolgál az egészség?"
    ]
  },
  {
    num: 2,
    name: "Ázsiai negyed",
    desc: "Kismillió fura ember, akikről azt sem tudod, valójában mit csinálnak.",
    x: 3,
    y: 1,
    pop: Math.floor(1500 + Math.random() * 1000),
    mtn: 0,
    exp: 0,
    niv: Math.floor(0 + Math.random() * 20),
    joy: Math.floor(0 + Math.random() * 20),
    def: Math.floor(5 + Math.random() * 20),
    ufo: 0,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: .7,
    culto: 1,
  },
  {
    num: 3,
    name: "Városliget",
    desc: "Sportpályák, játszóterek, csónakázótó a kikapcsolódni vágyóknak.",
    x: 1,
    y: 2,
    pop: Math.floor(50 + Math.random() * 300),
    mtn: 0,
    exp: 0,
    niv: Math.floor(40 + Math.random() * 30),
    joy: Math.floor(50 + Math.random() * 30),
    def: Math.floor(40 + Math.random() * 30),
    ufo: 0,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: 1,
    culto: 1,
  },
  {
    num: 4,
    name: "Városközpont",
    desc: "Itt van többek között a Városháza erődszerű épülete.",
    x: 2,
    y: 2,
    pop: Math.floor(800 + Math.random() * 500),
    mtn: 0,
    exp: 0,
    niv: Math.floor(55 + Math.random() * 45),
    joy: Math.floor(30 + Math.random() * 40),
    def: Math.floor(70 + Math.random() * 50),
    ufo: Math.floor(1 + Math.random() * 40),
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: 1.3,
    culto: 1,
  },
  {
    num: 5,
    name: "Üzleti negyed",
    desc: "A legnagyobb pénzintézetek és cégek központjainak felhőkarcolói magasodnak itt.",
    x: 3,
    y: 2,
    pop: Math.floor(800 + Math.random() * 600),
    mtn: 0,
    exp: 0,
    niv: Math.floor(70 + Math.random() * 30),
    joy: Math.floor(35 + Math.random() * 35),
    def: Math.floor(40 + Math.random() * 25),
    ufo: 0,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1.3,
    defo: 1.3,
    culto: 1,
  },
  {
    num: 6,
    name: "Ipartelep",
    desc: "Működő és bezárt gyárak, munkásszállók nyomasztó rengetege.",
    x: 1,
    y: 3,
    pop: Math.floor(1000 + Math.random() * 700),
    mtn: 0,
    exp: 0,
    niv: Math.floor(5 + Math.random() * 25),
    joy: Math.floor(0 + Math.random() * 5),
    def: Math.floor(10 + Math.random() * 20),
    ufo: 0,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1.3,
    defo: .7,
    culto: .7,
  },
  {
    num: 7,
    name: "Lakónegyed",
    desc: "Sok polgár lakhelye sok lehetőséggel. Itt van a Branyiszkó-tér is.",
    x: 2,
    y: 3,
    pop: Math.floor(2000 + Math.random() * 1000),
    mtn: 0,
    exp: 0,
    niv: Math.floor(30 + Math.random() * 40),
    joy: Math.floor(20 + Math.random() * 50),
    def: Math.floor(40 + Math.random() * 30),
    ufo: 0,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: 1,
    culto: .7,
  },
  {
    num: 8,
    name: "Kultúrnegyed",
    desc: "Színvonalas kultúrintézmények pezsgő éjszakai élettel.",
    x: 3,
    y: 3,
    pop: Math.floor(700 + Math.random() * 500),
    mtn: 0,
    exp: 0,
    niv: Math.floor(65 + Math.random() * 35),
    joy: Math.floor(75 + Math.random() * 25),
    def: Math.floor(30 + Math.random() * 70),
    ufo: 0,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1.3,
    defo: 1,
    culto: 1.3,
  }
];