window.ker = [
  {
    num: 0,
    name: "Erdőszél",
    desc: "Egészséges, pihentető túrák, hőssegédek és bűvös lények otthona.",
    x: 1,
    y: 1,
    pop: Math.floor(1 + Math.random() * 100),
    mtn: 0,
    exp: 0,
    niv: Math.floor(30 + Math.random() * 30),
    joy: Math.floor(70 + Math.random() * 30),
    def: Math.floor(40 + Math.random() * 30),
    ufo: 70,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: .7,
    defo: 1,
    culto: 1,
    szar: "pop_>_3000",
    vélemény: [
      {
        cond: "ufo_>_500",
        duma: ["Kicsit furák ezek az erdei lények. Neked nem?",
          "kjh[ÄfsdfđĐ[đĐ... Én... vagyok... ihbdifurigk... Nem.",
          "Éjjelente olyan, mintha mozognának a fák! Hátborzongató!",
          "Bzzzzzzz... Mezonscanelésem szerint most már agytumorod van!",
          "Bübü! Bübü! Gurgurgul. Etejóka, pípíííí!",
          "Egyre több itt az új faj. Vajon mutánsok vagy földönkívüliek?"]
      },
      {
        cond: "had_<_-50",
        duma: ["Félek tőlük! Rettegek! Ott vannak mindenhol!",
          "Eleinte még aranyosak voltak ezek a lények, de most már egyre agresszívebbek!",
          "Itt van például ez a mosolygós kis fa... Ááááá! Letépte a karom!!! A barom!!!",
          "Üdvözöllek, földlakó! Mi vagyunk szadisták. Elpusztítunk titeket!",
          "Csináljon valamit, polgi! Ezek az erdei lények kinyírnak minket!!!",
          "Meghackelik a gondolatainkat és olyan büdöseket finganak, hogy el lehet tőle kárhozni!"]
      },
      {
        cond: "joy_<_20",
        duma: ["Ez egy bűnös hely. Egy bűnös város.",
          "Én már csak egy megfelelő fát meg kötelet keresek...",
          "Utállak téged! Bíztunk benned, de csalódtunk! Takarodj!",
          "Szerinted miért élek itt? Lehet abban a rothadó városban élni??!!",
          "Ez korábban egy üde, kellemes hely volt, de tönkretetted!"]
      },
      {
        cond: "niv_<_20",
        duma: ["No money, no problem!",
          "A romlott társadalom anyagilag tönkretett. Most itt próbálok békére találni.",
          "Éppenséggel élhetnénk itt is egy kicsit magasabb színvonalon. Ez még nem a mélydzsungel!",
          "Ennyi pénzből nem lehet utánpótlást nevelni! Mi lesz így a sporttal?"]
      },
      {
        cond: "pop_<_100",
        duma: ["Jó ez a csend és nyugalom, de lassan kihalunk...",
          "Mindig erre a magányra vágytam!",
          "Jé, egy ember!"]
      },
      {
        cond: "def_>_100",
        duma: ["Minek ide ennyi rendőr? Itt mi békében élünk az erdei lényekkel!",
          "A sok egyenruhás fickó már veszélyezteti az erdő szabad világát!"]
      },
      {
        cond: "pop_>_3000",
        duma: ["Sosem volt ilyen tömegnyomor itt!",
          "Nem lehet már nyugodtan szarni a bokorban, annyian vannak!",
          "Elveszett a régi csend és nyugalom!"]
      },
      {
        cond: "joy_>_75",
        duma: ["Itt végre megtaláltam a belső békém.",
          "Sej-haj, oly vidám a vándor élet!",
          "Jöjjön, mutatok egy gyönyörű tájat!",
          "Ez a legjobb hely az egész városban!",
          "A boldogság titka: az Erdőszél!"]
      },
    ],
    semmi: [
      "Ha ön a polgármester, igazán fejleszthetné ezt az elvadult környéket!",
      "Éppen hugyoznék... Nem tudsz másvalakit kérdezni?",
      "Fütyfürüty! Szép az élet, csicseregnek a madarak! Madarak?",
      "A legfontosabb a tiszta sport és a minőségi utánpótlás-nevelés!",
      "Üdv! Ügyes Frigyes vagyok, az ezermester! Mit kell elintézni?",
      "Az ember kijön ide békésen meditálni... Erre a pofájába nyomnak egy mikrofont!",
      "Mi van? Nem voltál még erdőben? Hát milyen lenne?",
      "Érdekes itt az élővilág. Szerinted ez növény vagy állat?",
      "A legfontosabb a szeretet. Akit szeretsz, az sosem hal meg!",
      "Ha Isten nem Szentháromság, akkor nincs értelme a teremtésnek.",
      "Cssssss! Hallgasd a természet hangjait...",
      "Megmutatom, hogy lehet természetes módszerekkel, köveket verve igazi ökölvívóvá válni!",
      "Itt születnek a valódi legendák és a... favágók!"
    ]
  },
  {
    num: 1,
    name: "Farmok",
    desc: "Szorgos, egyszerű gazdálkodók földjei.",
    x: 2,
    y: 1,
    pop: Math.floor(150 + Math.random() * 400),
    mtn: 0,
    exp: 0,
    niv: Math.floor(5 + Math.random() * 25),
    joy: Math.floor(25 + Math.random() * 50),
    def: Math.floor(35 + Math.random() * 30),
    ufo: 50,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: .7,
    defo: .7,
    culto: 1,
    szar: "niv_>_75",
    vélemény: [
      {
        cond: "had_<_-5",
        duma: ["Jól vagyunk. Csak néha jönnek óriások le a hegyről.",
          "Pitymallatkor fura hangok gyünnek az erdőbű...",
          "Agyon kéne vágni ezeket az óriásokat! Én mondom, ezek nem hoznak semmi jót!",
          "Valami ludvércek viszik a birkáinkat éjjel, hogy ütné agyon őket az Isten nyila!",
          "A minap egy markoláb elvitte a disznómat! Csinálni kell valamit!"
        ]
      },
      {
        cond: "had_>_60",
        duma: [
          "Hát, most már jó. Nem nagyon gyünnek már azok a fene nagy óriások!",
          "Amikor az a pandúr jól nyakoncsípte azt a pomogácsot, az betyáros volt ám!",
          "Igaz, hogy kevesebb a tolvaj lidérc, de már túl sok a pandúr itt, kérem alásan!"
        ]
      },
      {
        cond: "pop_<_300",
        duma: [
          "Fogyunk, kérem, egyre csak fogyunk!",
          "Nem bírunk ilyen kevesen szántani! Megdöglött a Riska is! Mi lesz igy vélünk?",
          "Nem tudjuk bétakarítani a termést! Nincs elíg ámbör!"
        ]
      },
      {
        cond: "niv_<_20",
        duma: [
          "Vagyogatunk. Szegínyesön, de böcsülettöl!",
          "Megkínálnám szívesen, de nincs mibűl!",
          "Hát, kérem, itt nálunk mindig nenéz az élet!",
          "A fene akart paraszt lenni! Inkább lennék iparos!"
        ]
      },
      {
        cond: "niv_>_75",
        duma: [
          "Mióta bejöttek ezek a kütymük, a gyerekek folyton csak azokat nyomkodják, a tyúkok meg éheznek!",
          "Egyszerű élethez vagyunk mi hozzászokva, nem ehhez a sok... csilivilihez!",
          "Megmondom én kerek-perec: nem kell nékünk ez a sok fejlődés! Jó volt apáink útja?",
          "Akinek sok a pénze, az csak elissza a kocsmában! Ahelyett, hogy dógozna!"
        ]
      },
      {
        cond: "joy_>_75",
        duma: [
          "Jól vagyunk, az anyja keservit, jól!",
          "Ihaj-csuhaj, sallárom! Lett már nékem talárom!",
          "Jöjjön, iszunk magára! Isten-Isten!",
          "Húzzad, cigány, eliszom az utolsó garasom is!",
        ]
      },
    ],
    semmi: [
      "Kicsit büdös van, de azért... hát, csak büdös van, na!",
      "Pillanat, még megetetem a tyúkokat...",
      "Osztán minek köszönhetjük a látogatást?",
      "Hogy szolgál az egészség?",
      "Dolgozunk mi mindég! De a lurkóknak mindig van pár pofonunk! Érzik is a törődést!",
    ]
  },
  {
    num: 2,
    name: "Ázsiai negyed",
    desc: "Kismillió fura ember, akikről azt sem tudod, valójában mit csinálnak.",
    x: 3,
    y: 1,
    pop: Math.floor(1500 + Math.random() * 1000),
    mtn: 0,
    exp: 0,
    niv: Math.floor(0 + Math.random() * 20),
    joy: Math.floor(0 + Math.random() * 20),
    def: Math.floor(5 + Math.random() * 20),
    ufo: 10,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: .7,
    culto: 1,
    szar: "def_>_500",
    vélemény: [
      {
        cond: "had_<_-100",
        duma: ["Csen Jüt elvitték ufók.",
          "Vannak zöld ember ott kert. Kici, mint mi, cak zöld.",
          "Mi kérdez zöld ember új recept. Te kóstol? Kicit édes, kicit szavanyú, de már miénk.",
          "Baba Jaga jár mindig mi kert. Visz kutya, galamb, articóka, minden!",
        ]
      },
      {
        cond: "def_>_500",
        duma: [
          "Sok rendőr és katona! Nem jó üzlet. Nem jó.",
          "Inkább zöld ember, mint nagy rendőr! Mi fél.",
          "Nem tudjuk ápolni jakuza hagyományainkat. Mindenbe beleütik az orrukat a fakabátok!",
          "Nem kell rendőr! Tong vigyáz magára. Mindig megold."
        ]
      },
      {
        cond: "pop_<_500",
        duma: [
          "Egyre kevesebb ázsiai itt. Mi lesz, ha mi elfogy?",
          "Régen sokkal több ember itt! Akkor ment üzlet jól!",
          "Nagy családok vannak a kihalás szélén! Szégyent hozunk apáinkra!"
        ]
      },
      {
        cond: "pro_<_1000",
        duma: [
          "Egyre kevesebb pénz! Senki vesz gumi dugó! Nem kell gumi dugó? Óccó.",
          "Nézd, van nekem szög. Nem rozda az, feszték! Színes szög. Cak száz! Jó szög!",
          "Finom husit adok óccón! Nem macka. Kisseb.",
          "Te elront üzlet! Régen üzlet virágzó, most semmi! Te inkább megdöglik!"
        ]
      },
    ],
    semmi: [
      "Szia, uram! Turbó csiga érdekel? Ezeöccá! Nem drága.",
      "Van jó zokni! Original Zara! Ezerér tiéd!",
      "Jöjjön! Van nálunk friss vízi hal! Nem drága.",
      "Masszázs? Van itt szép lányok. Te leszesz boldog!",
      "Van finom kaca! Háp-háp! Gyere be!",
      "Nézd! Villogó gyík! Gyerek szeret! Vegyél gyerek villogó gyík!",
      "A megvilágosodás útja olyan, mint ahogy a csiga kúszik a cseresznyefán.",
      "Készüljetek! Megrázta a hóoroszlán a bajszát. Elkezdődött..."
    ]
  },
  {
    num: 3,
    name: "Városliget",
    desc: "Sportpályák, játszóterek, csónakázótó a kikapcsolódni vágyóknak.",
    x: 1,
    y: 2,
    pop: Math.floor(50 + Math.random() * 300),
    mtn: 0,
    exp: 0,
    niv: Math.floor(40 + Math.random() * 30),
    joy: Math.floor(50 + Math.random() * 30),
    def: Math.floor(30 + Math.random() * 30),
    ufo: 20,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: 1,
    culto: 1,
    szar: "had_>_70",
  },
  {
    num: 4,
    name: "Városközpont",
    desc: "Itt van többek között a Városháza erődszerű épülete.",
    x: 2,
    y: 2,
    pop: Math.floor(800 + Math.random() * 500),
    mtn: 0,
    exp: 0,
    niv: Math.floor(55 + Math.random() * 45),
    joy: Math.floor(30 + Math.random() * 40),
    def: Math.floor(70 + Math.random() * 50),
    ufo: Math.floor(1 + Math.random() * 30),
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: 1.3,
    culto: 1,
    szar: "had_<_40",
  },
  {
    num: 5,
    name: "Üzleti negyed",
    desc: "A legnagyobb pénzintézetek és cégek központjainak felhőkarcolói magasodnak itt.",
    x: 3,
    y: 2,
    pop: Math.floor(800 + Math.random() * 600),
    mtn: 0,
    exp: 0,
    niv: Math.floor(70 + Math.random() * 30),
    joy: Math.floor(35 + Math.random() * 35),
    def: Math.floor(40 + Math.random() * 25),
    ufo: 1,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1.3,
    defo: 1.3,
    culto: 1,
    szar: "niv_<_50",
  },
  {
    num: 6,
    name: "Ipartelep",
    desc: "Működő és bezárt gyárak, munkásszállók nyomasztó rengetege.",
    x: 1,
    y: 3,
    pop: Math.floor(1000 + Math.random() * 700),
    mtn: 0,
    exp: 0,
    niv: Math.floor(5 + Math.random() * 25),
    joy: Math.floor(0 + Math.random() * 5),
    def: Math.floor(10 + Math.random() * 20),
    ufo: 5,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1.3,
    defo: .7,
    culto: .7,
    szar: "pro_<_1500",
  },
  {
    num: 7,
    name: "Lakónegyed",
    desc: "Sok polgár lakhelye sok lehetőséggel. Itt van a Branyiszkó-tér is.",
    x: 2,
    y: 3,
    pop: Math.floor(2000 + Math.random() * 1234),
    mtn: 0,
    exp: 0,
    niv: Math.floor(30 + Math.random() * 40),
    joy: Math.floor(20 + Math.random() * 50),
    def: Math.floor(40 + Math.random() * 30),
    ufo: Math.floor(Math.random() * 10),
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1,
    defo: 1,
    culto: .7,
    szar: "pop_<_1500",
  },
  {
    num: 8,
    name: "Kultúrnegyed",
    desc: "Színvonalas kultúrintézmények pezsgő éjszakai élettel.",
    x: 3,
    y: 3,
    pop: Math.floor(700 + Math.random() * 500),
    mtn: 0,
    exp: 0,
    niv: Math.floor(65 + Math.random() * 35),
    joy: Math.floor(75 + Math.random() * 25),
    def: Math.floor(30 + Math.random() * 70),
    ufo: 0,
    had: 0,
    pro: 0,
    popC: 0,
    popCD: 0,
    mtnC: 0,
    mtnCD: 0,
    expC: 0,
    expCD: 0,
    nivC: 0,
    nivCD: 0,
    joyC: 0,
    joyCD: 0,
    defC: 0,
    defCD: 0,
    ufoC: 0,
    ufoCD: 0,
    hadC: 0,
    hadCD: 0,
    proC: 0,
    proCD: 0,
    dev: [],
    evs: [-1, -1],
    eco: 1.3,
    defo: 1,
    culto: 1.3,
    szar: "joy_<_50",
  }
];